### ISSUE TITLE
Example Test Cases

### ISSUE THREAD

**Issue by cratelyn** [fastly/compute-starter-kit-rust-default#2]
We have a high-level issue for this with ECP-81, but this issue is implicitly focused on _integration_ tests that run end-to-end. That's definitely worth doing in the long term, but will (as mentioned in the ticket) require some heavier lifting.

We can fix a lot of this friction around testing with a template that tests `handle_request` directly, providing example `Request<Body>` inputs and checking that the results look as expected. This sidesteps the long-term need for a local HTTP server :slightly_smiling_face: 

I could imagine a world where `handle_request` accepts some sort of `dyn` trait object, which would mock out downstream interactions. This is a common pattern for testing in Rust, but leads to my one concern about whether this is doable. A possible tradeoff that we might run into here is that this could potentially lead to some really heinous type signatures.

**Comment by softprops** [comment]
> We can fix a lot of this friction around testing with a template that tests handle_request directly, providing example Request<Body> inputs and checking that the results look as expected. 

How does one construct these types in a unit test. I've found that I can't actually test code that relies on the `Body` type because of `abi` references that I don't reply on environmental factors.

Here's an example snippet from code that `Body::new()` invokes

```
impl BodyHandle { 
 ...
  pub fn new() -> Self {
        let mut handle = BodyHandle::INVALID;
        let status = unsafe { abi::xqd_body_new(handle.as_u32_mut()) };
        match status.result().map(|_| handle) {
            Ok(h) if h.is_valid() => h,
            _ => panic!("xqd_body_new failed"),
        }
    }
}
```

I'll get the following error in a simple test that doesn't get much farther than `Request::builder().uri("/").body(Body::new())?;`

```
cargo wasi test -- --no-capture                                                                                                                                                 


Caused by:
    0: failed to instantiate ".../target/wasm32-wasi/debug/deps/fastly_template_rust_default-fe75b81a015ab418.wasm"
    1: unknown import: `env::xqd_body_new` has not been defined
```

**Comment by softprops** [comment]
Is the fastly crate available as an accessible GitHub repo? I'd love to help improve the testing story for these.

**Comment by jregistr** [comment]
👋 Hello!
How do you actually write tests in this template? I've tried running the simplest possible tests in `main.rs` like 
```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add() {
        assert_eq!(1, 1);
    }
}
```
and those fail to run. It appears to be related to the file in the `bin` directory from the compile step.
```
target/wasm32-wasi/debug/deps/fastly_template_rust_default-32eb535a27d99ab9.wasm
/Users/.../temporary-fastly-cmp/target/wasm32-wasi/debug/deps/fastly_template_rust_default-32eb535a27d99ab9.wasm: /Users/.../temporary-fastly-cmp/target/wasm32-wasi/debug/deps/fastly_template_rust_default-32eb535a27d99ab9.wasm: cannot execute binary file
error: test failed, to rerun pass '--bin fastly-template-rust-default'
```

**Comment by peterjmag** [comment]
@jregistr I was wondering the same thing. Here's one workaround:

```sh
cargo test --target="x86_64-apple-darwin"
# OR replace with the right target for your machine from: rustup show | grep 'Default host'
```

(I also aliased this to `cargo test_mac` per [this suggestion on StackOverflow](https://stackoverflow.com/a/66793839/349353).)

This isn't a great solution though, because it assumes a single target, which means you wouldn't be able to use the same command for running tests in CI (for instance). I'm new to Rust, so maybe someone else has a better idea?

**Comment by cratelyn** [comment]
:wave: hi everybody!

i believe this issue is mostly covered by the [release](https://www.fastly.com/blog/new-compute-edge-local-testing-puts-you-in-control-of-your-testing-setup) of a local testing feature for Compute@Edge.

this functionality is exposed through the Fastly CLI, via a `fastly compute serve` command that will run your program locally. you can learn more about how to run and configure this server on the developer portal [here](https://developer.fastly.com/learning/compute/testing/#running-a-local-testing-server).

you can also find the _source_ for this local testing daemon publicly on GitHub [here](https://github.com/fastly/Viceroy/). PR's and issues are welcome!

today, this currently provides a building block that can be used for integration tests, but doesn't fully answer some of the unit-testing questions raised here. we should have more answers about that soon, fastly/Viceroy#56 tracks some of the prerequisite work for improving the unit-testing story.

given all of this, i'm going to close this issue now, and perhaps we can move further discussions over to the Viceroy repository. thank you :love_letter:
